version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - volume_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: products
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=products
      - DATABASE_PORT=3306
volumes:
  volume_mysql: {}